[build]
  publish = "public"
  command = "npm install && hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.157.0" # Match your local version
  HUGO_ENV = "production"
  NODE_VERSION = "26.0.0"
  GO_VERSION = "1.26.3"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"